Repository NUreserved/NUreserved, pull requests merged in 2024-12, with the labels that each got.

#25 Add room usage rules UI screen
  app/src/main/java/com/it235/nureserved/RoomUsageRulesScreen.kt
Labels: Type: Enhancement, Status: In Progress, Priority: High

#3 Add room reservation form UI
  app/src/main/java/com/it235/nureserved/MainActivity.kt
  app/src/main/java/com/it235/nureserved/Routes.kt
  app/src/main/java/com/it235/nureserved/composables/Composables.kt
  app/src/main/java/com/it235/nureserved/ui/ReservationFormScreen.kt
  app/src/main/java/com/it235/nureserved/ui/RoomUsageRulesScreen.kt
  app/src/main/java/com/it235/nureserved/ui/homesreenui/HomeScreen.kt
  app/src/main/res/drawable/check_circle.xml
  app/src/main/res/drawable/sticky_note_2.xml
Labels: Type: Enhancement, Status: In Progress, Priority: High

#19 Add room reservation status tab UI
  app/src/main/java/com/it235/nureserved/MainActivity.kt
  app/src/main/java/com/it235/nureserved/Routes.kt
  app/src/main/java/com/it235/nureserved/ui/homesreenui/HomeScreen.kt
  app/src/main/java/com/it235/nureserved/ui/reservationscreenui/ReservationFilledOutFormScreen.kt
  app/src/main/java/com/it235/nureserved/ui/reservationscreenui/ReservationStatusScreen.kt
  app/src/main/res/drawable-nodpi/sample_room.jpg
Labels: Type: Enhancement, Status: In Progress, Priority: High

#11 Add terms and condition screen UI
  app/src/main/java/com/it235/nureserved/MainActivity.kt
  app/src/main/java/com/it235/nureserved/Routes.kt
  app/src/main/java/com/it235/nureserved/ui/TermsAndConditionsScreen.kt
  app/src/main/java/com/it235/nureserved/ui/homesreenui/HomeScreen.kt
Labels: Type: Enhancement, Priority: Low

#35 Fix rendering issues on `RoomReservationStatusScreen` and `ReservationFilledOutFormScreen`
  app/src/main/java/com/it235/nureserved/MainActivity.kt
  app/src/main/java/com/it235/nureserved/Routes.kt
  app/src/main/java/com/it235/nureserved/ui/homesreenui/HomeScreen.kt
  app/src/main/java/com/it235/nureserved/ui/reservationscreenui/ReservationFilledOutFormScreen.kt
  app/src/main/java/com/it235/nureserved/ui/reservationscreenui/ReservationStatusScreen.kt
Labels: Type: Enhancement, Priority: High

#42 Use app-defined theme colors and disable dynamic color theming
  app/build.gradle.kts
  app/src/main/java/com/it235/nureserved/ui/theme/Color.kt
  app/src/main/java/com/it235/nureserved/ui/theme/Theme.kt
  app/src/main/java/com/it235/nureserved/ui/theme/Type.kt
  gradle/libs.versions.toml
Labels: Type: Enhancement, Priority: Medium

#43 Move all screens to a single package for better organization
  app/src/main/java/com/it235/nureserved/MainActivity.kt
  app/src/main/java/com/it235/nureserved/ui/screens/ReservationFormScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/RoomUsageRulesScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/SplashScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/TermsAndConditionsScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/LoginScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/SignUpScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/HomeScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/RoomDetails.kt
  app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationFilledOutFormScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationStatusScreen.kt
Labels: Type: Enhancement, Priority: Low

#44 Fix system config change causes the app to go to splash screen
  app/src/main/java/com/it235/nureserved/MainActivity.kt
Labels: Type: Bug, Priority: Critical

#45 Add schedule viewer grid in RoomDetails screen
  app/src/main/java/com/it235/nureserved/MainActivity.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/roomdetails/RoomDetails.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/roomdetails/model.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/roomdetails/sampleData.kt
  app/src/main/java/com/it235/nureserved/ui/theme/Color.kt
  app/src/main/res/drawable/chevron_left.xml
  app/src/main/res/drawable/chevron_right.xml
Labels: Type: Enhancement, Priority: High

#47 Make app theme responsive on system theme change
  app/src/main/java/com/it235/nureserved/composables/Composables.kt
  app/src/main/java/com/it235/nureserved/ui/screens/ReservationFormScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationFilledOutFormScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationStatusScreen.kt
  app/src/main/java/com/it235/nureserved/ui/theme/Color.kt
Labels: Type: Enhancement, Priority: High

#48 Redesign the reservation filled out form screen
  app/src/main/java/com/it235/nureserved/MainActivity.kt
  app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationFilledOutFormScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationStatusScreen.kt
  app/src/main/java/com/it235/nureserved/ui/theme/Color.kt
Labels: Type: Enhancement, Priority: Medium

#52 Rework signup screen
  app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/SignUpScreen.kt
Labels: Type: Enhancement, Priority: Low

#54 Reservation form enhancements
  app/src/main/java/com/it235/nureserved/composables/Composables.kt
  app/src/main/java/com/it235/nureserved/ui/screens/ReservationFormScreen.kt
Labels: Type: Enhancement, Priority: Medium

#58 Fix navigation issues
  app/src/main/java/com/it235/nureserved/ui/screens/RoomUsageRulesScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/HomeScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationStatusScreen.kt
Labels: Type: Bug, Type: Enhancement, Priority: High

#65 Visual modifications of signup and login screens
  app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/LoginScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/SignUpScreen.kt
Labels: Type: Enhancement, Priority: Medium

#68 Change app icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: Type: Enhancement, Priority: Medium

#66 Use snackbar instead of dialog for showing login/signup errors
  app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/LoginScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/SignUpScreen.kt
Labels: Type: Enhancement, Priority: Medium

#71 Show filter icon when user is in home tab only
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/HomeScreen.kt
Labels: Type: Enhancement, Priority: Medium

#72 Remove reserve tab in home screen and use FAB instead
  app/src/main/java/com/it235/nureserved/composables/Composables.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/HomeScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/roomdetails/RoomDetails.kt
Labels: Type: Enhancement, Priority: Medium

#70 Use dummy data to lessen hardcoded data values
  app/src/main/java/com/it235/nureserved/MainActivity.kt
  app/src/main/java/com/it235/nureserved/data/rooms/mock_data.kt
  app/src/main/java/com/it235/nureserved/data/rooms/model.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/HomeScreen.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/RoomDetails.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/roomdetails/model.kt
  app/src/main/java/com/it235/nureserved/ui/screens/homesreenui/roomdetails/sampleData.kt
  app/src/main/res/drawable-nodpi/resource_default.png
  app/src/main/res/drawable-nodpi/room_202.jpg
  app/src/main/res/drawable-nodpi/room_205.jpg
  app/src/main/res/drawable-nodpi/room_303.jpg
  app/src/main/res/drawable-nodpi/room_305.jpg
  app/src/main/res/drawable-nodpi/room_506.jpg
  app/src/main/res/drawable-nodpi/room_508.jpg
Labels: Type: Enhancement, Priority: Medium

#76 Add tracking number for reservation status screen
  app/src/main/java/com/it235/nureserved/ui/screens/reservationscreenui/ReservationFilledOutFormScreen.kt
Labels: Type: Enhancement, Priority: Medium

#79 Allow multiple selection and deselection of venue in reservation form screen
  app/src/main/java/com/it235/nureserved/ui/screens/ReservationFormScreen.kt
Labels: Type: Enhancement, Priority: Medium

#87 Change program text field to dropdown menu
  app/src/main/java/com/it235/nureserved/ui/screens/authscreenui/signup/ProgramStudentNumberFieldsScreen.kt
  app/src/main/res/drawable/baseline_arrow_drop_down_24.xml
  app/src/main/res/drawable/baseline_arrow_drop_up_24.xml
Labels: Type: Enhancement, Priority: Medium
